### ISSUE TITLE
Не удаётся попасть на сервер oauth

### ISSUE THREAD

**Issue by ogizesh** [Mon4ik/yandex-homekit#4]
5 пункт. Непонятно вообще что делать. Мне выдаёт сервер стартед в терминале на хоумбридж и 127.0.0.1:13370
Как попасть на сервер oauth?

**Comment by Mon4ik** [comment]
Веб сервер запускается на порту :13370 и надо зайти на него через браузер

**Comment by ogizesh** [comment]
у меня не открывается конфиг по /home/admin/.yandex-homekit/config.json

**Comment by ogizesh** [comment]
он просто открывает хоумбридж и всё, в конфиге хоумбриджа вообще ничего не вижу

**Comment by Mon4ik** [comment]
Конфиг файл надо создать по пути

Проект теперь не связан с Homebridge, он теперь как независимый мост на HomeKit

**Comment by ogizesh** [comment]
А как создать на хоумбридже конфиг нужный?

**Comment by iMazday** [comment]
Есть потребность в реализации установки для докера. 
Сейчас у меня на НАС QNAP  поднят сервер Hoobs (homebridge) в докере. Делаю установку по шагам, натыкаюсь на то, что не могу найти в папках докера конфигурационный файл и каталог  ~/.yandex-homekit/config.json 
Не понимаю, куда копать, прошу совета.

**Comment by Mon4ik** [comment]
> Есть потребность в реализации установки для докера. 
> 
> Сейчас у меня на НАС QNAP  поднят сервер Hoobs (homebridge) в докере. Делаю установку по шагам, натыкаюсь на то, что не могу найти в папках докера конфигурационный файл и каталог  ~/.yandex-homekit/config.json 
> 
> Не понимаю, куда копать, прошу совета. 

~ - это домашний каталог юзера, например если это рут, то это будет /root. Так же можно запустить nodejs и выполнить `os.homedir()` для получения домашнего каталога

**Comment by ogizesh** [comment]
а на raspberry pi с установленным хоумбридж можно как-то этот плагин использовать?

**Comment by Mon4ik** [comment]
> а на raspberry pi с установленным хоумбридж можно как-то этот плагин использовать?
> 
> 

Это не плагин на homebridge, это отдельное приложение не связанное с homebridge
